import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { bindings } from '../bindings/api.mjs';

const parameterParts = (args) => {
  if (!args) return [];
  const parts = [];
  let depth = 0, start = 0;
  for (let i = 0; i < args.length; i++) {
    if ('([{'.includes(args[i])) depth++;
    else if (')]}'.includes(args[i])) depth--;
    else if (args[i] === ',' && depth === 0) { parts.push(args.slice(start, i)); start = i + 1; }
  }
  parts.push(args.slice(start));
  return parts.map(arg => arg.trim());
};
const parameterNames = args => parameterParts(args).map(arg => arg.split(':')[0].trim());
const declaration = (type, name, args, returns) =>
  `pub extern "js" fn ${type}::${name}(${args}) -> ${returns}`;
const check = process.argv.includes('--check');
const output = (path, source) => {
  if (check) {
    if (readFileSync(path, 'utf8') !== source) {
      console.error(`Stale binding: ${path.pathname}. Run just generate.`);
      process.exitCode = 1;
    }
  } else writeFileSync(path, source);
};

for (const { type, factory: primaryFactory, factories: extraFactories = [], methods, declare } of bindings) {
  const blocks = ['// Generated by scripts/generate.mjs from bindings/api.mjs. Do not edit.'];
  if (declare) blocks.push(`///|\n#external\npub type ${type}`);
  for (const factory of [...(primaryFactory ? [primaryFactory] : []), ...extraFactories]) {
    if (factory.throws) {
      const ffi = `ffi_create_${factory.name}`;
      blocks.push(`///|\n#module("@mizchi/three-mbt/${factory.module ?? 'constructors'}")\nextern "js" fn ${type}::${ffi}(${factory.args}) -> JsResult[${type}] = "${factory.js}"`);
      blocks.push(`///|\npub fn ${type}::${factory.name}(${factory.args}) -> ${type} raise ${factory.throws} { match ${type}::${ffi}(${parameterNames(factory.args).join(', ')}).into_result() { Ok(value) => value; Err(message) => raise ${factory.throws}(message) } }`);
      continue;
    }
    blocks.push(`///|\n#module("@mizchi/three-mbt/${factory.module ?? 'constructors'}")\n${declaration(type, factory.name, factory.args, type)} = "${factory.js}"`);
  }
  for (const { name, args = '', returns, js, expression, identity, nullable, option, static: isStatic, throws, async: isAsync, jsonArgs = [], jsonResult } of methods) {
    if (isStatic) {
      const symbol = `${type}_${name}`;
      const signature = nullable ? `extern "js" fn ${type}::ffi_${name}(${args}) -> Nullable[${returns}]` : declaration(type, name, args, returns);
      blocks.push(`///|\n#module("@mizchi/three-mbt/statics")\n${signature} = "${symbol}"`);
      if (nullable) blocks.push(`///|\npub fn ${type}::${name}(${args}) -> ${returns}? { ${type}::ffi_${name}(${parameterNames(args).join(', ')}).to_option() }`);
      continue;
    }
    if (identity) {
      blocks.push(`///|\npub fn ${type}::${name}(self : ${type}) -> ${returns} = "%identity"`);
      continue;
    }
    if (option) {
      blocks.push(`///|\nextern "js" fn ${type}::ffi_${name}(self : ${type}, value : Nullable[${option}]) -> Unit =\n  #| (self, value) => ${expression}`);
      blocks.push(`///|\npub fn ${type}::${name}(self : ${type}, value : ${option}?) -> Unit { self.ffi_${name}(Nullable::from_option(value)) }`);
      continue;
    }
    if (throws) {
      const names = parameterNames(args);
      const ffiArgs = parameterParts(args).map(arg => {
        const name = arg.split(':')[0].trim();
        return jsonArgs.includes(name) ? arg.replace(/: Json\b/, ': String') : arg;
      }).join(', ');
      const ffiParameters = `self : ${type}${ffiArgs ? `, ${ffiArgs}` : ''}`;
      const parameters = `self : ${type}${args ? `, ${args}` : ''}`;
      const resultType = jsonResult ? 'String' : returns;
      const body = expression ?? `self.${js}(${names.join(', ')})`;
      const params = ['self', ...names].join(', ');
      const evaluate = `(() => ${body})()`;
      const ffiReturn = isAsync ? `@js_async.Promise[${resultType}]` : `JsResult[${resultType}]`;
      const ffiBody = isAsync ? `Promise.resolve().then(() => ${body})` : `{ try { return { ok: true, value: ${evaluate} }; } catch (error) { return { ok: false, error: String(error) }; } }`;
      blocks.push(`///|\nextern "js" fn ${type}::ffi_${name}(${ffiParameters}) -> ${ffiReturn} =\n  #| (${params}) => ${ffiBody}`);
      const callArgs = names.map(n => jsonArgs.includes(n) ? `${n}.stringify()` : n).join(', ');
      const result = `self.ffi_${name}(${callArgs})`;
      const convert = !jsonResult ? 'value' : isAsync ? '@json.parse(value)' : `try @json.parse(value) catch { error => raise ${throws}((error : Error).to_string()) }`;
      const bodyMbt = isAsync
        ? `let value = ${result}.wait(); ${convert}`
        : `match ${result}.into_result() { Ok(value) => ${convert}; Err(message) => raise ${throws}(message) }`;
      const checkedBody = isAsync ? `try { ${bodyMbt} } catch { error => raise ${throws}((error : Error).to_string()) }` : bodyMbt;
      blocks.push(`///|\npub ${isAsync ? 'async ' : ''}fn ${type}::${name}(${parameters}) -> ${returns} raise ${throws} { ${checkedBody} }`);
      continue;
    }
    const params = ['self', ...parameterNames(args)];
    const body = expression ?? `self.${js}(${parameterNames(args).join(', ')})`;
    const parameters = `self : ${type}${args ? `, ${args}` : ''}`;
    if (nullable) {
      blocks.push(`///|\nextern "js" fn ${type}::ffi_${name}(${parameters}) -> Nullable[${returns}] =\n  #| (${params.join(', ')}) => ${body}`);
      blocks.push(`///|\npub fn ${type}::${name}(${parameters}) -> ${returns}? { self.ffi_${name}(${parameterNames(args).join(', ')}).to_option() }`);
    } else {
      blocks.push(`///|\n${declaration(type, name, parameters, returns)} =\n  #| (${params.join(', ')}) => ${body}`);
    }
  }
  const path = new URL(`../src/${type.toLowerCase()}_generated.mbt`, import.meta.url);
  const source = execFileSync('moonfmt', ['-'], { input: blocks.join('\n\n') + '\n', encoding: 'utf8' });
  output(path, source);
}

const factories = bindings.flatMap(b => [...(b.factory ? [b.factory] : []), ...(b.factories ?? [])].map(factory => ({...b, factory}))).filter(b => b.declare && !b.factory.module);
const className = b => b.type === 'BufferAttribute' ? 'Float32BufferAttribute' : b.type;
const js = ['// Generated by scripts/generate.mjs. Do not edit.',
  `import { ${[...new Set(factories.map(className))].join(', ')} } from 'three';`, ''];
for (const binding of factories) {
  const params = parameterNames(binding.factory.args);
  const args = binding.type.endsWith('Material') ? `{ ${params.map(p => binding.factory.options?.[p] ? `${binding.factory.options[p]}: ${p}` : p).join(', ')} }` : params.join(', ');
  js.push(`export const ${binding.factory.js} = (${params.join(', ')}) => new ${className(binding)}(${args});`);
}
output(new URL('../js/core-factories.js', import.meta.url), js.join('\n') + '\n');

const staticBindings = bindings.filter(b => b.methods.some(m => m.static));
const statics = ['// Generated by scripts/generate.mjs. Do not edit.',
  `import { ${staticBindings.map(b => b.type).join(', ')} } from 'three';`, ''];
for (const binding of staticBindings) for (const method of binding.methods.filter(m => m.static)) {
  const params = parameterNames(method.args);
  statics.push(`export const ${binding.type}_${method.name} = (${params.join(', ')}) => ${method.expression ?? `${binding.type}.${method.js}(${params.join(', ')})`};`);
}
output(new URL('../js/static-methods.js', import.meta.url), statics.join('\n') + '\n');
