import { m, p, s, rw, expr, nullable, optional, upcast, node, geometry, material, identity, cls } from './helpers.mjs';

const map = (name, js = name) => [nullable(name, '', 'Texture', `self.${js}`), optional(name, 'Texture', js)];
const camera = () => [upcast('camera', 'Camera'), ...node(), m('update_projection_matrix', '', 'Unit', 'updateProjectionMatrix')];
const light = () => [upcast('light', 'Light'), ...node()];
const colorMaterial = () => [...material(), p('color', 'Color'), ...map('map')];

export const rendering = [
  cls('Camera', '', [...node(), p('projection_matrix', 'Matrix4', 'projectionMatrix'), p('projection_matrix_inverse', 'Matrix4', 'projectionMatrixInverse')], { factory: null }),
  cls('PerspectiveCamera', 'fov : Double, aspect : Double, near : Double, far : Double', [
    ...camera(), ...['fov', 'aspect', 'near', 'far', 'zoom'].flatMap(n => rw(n, 'Double')),
    m('set_focal_length', 'length : Double', 'Unit', 'setFocalLength'), m('get_focal_length', '', 'Double', 'getFocalLength'),
  ]),
  cls('OrthographicCamera', 'left : Double, right : Double, top : Double, bottom : Double, near : Double, far : Double', [
    ...camera(), ...['left', 'right', 'top', 'bottom', 'near', 'far', 'zoom'].flatMap(n => rw(n, 'Double')),
  ]),
  cls('BufferAttribute', '', [
    ...rw('name', 'String'),
    p('count', 'Int'), p('item_size', 'Int', 'itemSize'), p('normalized', 'Bool'),
    ...['x','y','z','w'].map(c => m(`get_${c}`, 'index : Int', 'Double', `get${c.toUpperCase()}`)),
    m('set_xyz', 'index : Int, x : Double, y : Double, z : Double', 'BufferAttribute', 'setXYZ'),
    m('get_component', 'index : Int, component : Int', 'Double', 'getComponent'),
    m('set_component', 'index : Int, component : Int, value : Double', 'BufferAttribute', 'setComponent'),
    expr('mark_needs_update', '', 'Unit', '{ self.needsUpdate = true; }'),
  ], { factory: { name: 'from_floats', args: 'values : FixedArray[Double], item_size : Int', js: 'float32BufferAttribute' } }),
  cls('BufferGeometry', '', [
    ...rw('morph_targets_relative', 'Bool', 'morphTargetsRelative'),
    expr('morph_attributes', 'name : String', 'FixedArray[BufferAttribute]', 'Object.hasOwn(self.morphAttributes, name) ? self.morphAttributes[name].slice() : []'),
    expr('set_morph_attributes', 'name : String, attributes : FixedArray[BufferAttribute]', 'Unit', '{ Object.defineProperty(self.morphAttributes, name, { value: attributes.slice(), writable: true, enumerable: true, configurable: true }); }'),
    p('id', 'Int'), ...rw('name', 'String'), identity('BufferGeometry'), m('clone', '', 'BufferGeometry'),
    m('set_attribute', 'name : String, attribute : BufferAttribute', 'BufferGeometry', 'setAttribute'),
    nullable('get_attribute', 'name : String', 'BufferAttribute', 'self.getAttribute(name)'),
    m('delete_attribute', 'name : String', 'BufferGeometry', 'deleteAttribute'),
    m('has_attribute', 'name : String', 'Bool', 'hasAttribute'),
    m('set_indices', 'indices : FixedArray[Int]', 'BufferGeometry', 'setIndex'),
    nullable('get_index', '', 'BufferAttribute', 'self.getIndex()'),
    m('compute_vertex_normals', '', 'Unit', 'computeVertexNormals'),
    m('compute_bounding_box', '', 'Unit', 'computeBoundingBox'),
    m('compute_bounding_sphere', '', 'Unit', 'computeBoundingSphere'),
    nullable('bounding_box', '', 'Box3', 'self.boundingBox'), nullable('bounding_sphere', '', 'Sphere', 'self.boundingSphere'),
    m('translate', 'x : Double, y : Double, z : Double', 'BufferGeometry'),
    m('scale', 'x : Double, y : Double, z : Double', 'BufferGeometry'),
    ...['x', 'y', 'z'].map(c => m(`rotate_${c}`, 'angle : Double', 'BufferGeometry', `rotate${c.toUpperCase()}`)),
    m('apply_matrix4', 'matrix : Matrix4', 'BufferGeometry', 'applyMatrix4'),
    m('center', '', 'BufferGeometry'), m('to_non_indexed', '', 'BufferGeometry', 'toNonIndexed'),
    m('set_draw_range', 'start : Int, count : Int', 'Unit', 'setDrawRange'),
    m('add_group', 'start : Int, count : Int, material_index : Int', 'Unit', 'addGroup'),
    m('clear_groups', '', 'Unit', 'clearGroups'), m('dispose'),
  ]),
  ...[
    ['BoxGeometry', 'width : Double, height : Double, depth : Double'],
    ['PlaneGeometry', 'width : Double, height : Double'],
    ['SphereGeometry', 'radius : Double, width_segments : Int, height_segments : Int'],
    ['CylinderGeometry', 'radius_top : Double, radius_bottom : Double, height : Double, radial_segments : Int'],
    ['ConeGeometry', 'radius : Double, height : Double, radial_segments : Int'],
    ['TorusGeometry', 'radius : Double, tube : Double, radial_segments : Int, tubular_segments : Int'],
    ['TorusKnotGeometry', 'radius : Double, tube : Double, tubular_segments : Int, radial_segments : Int'],
    ['CircleGeometry', 'radius : Double, segments : Int'],
    ['RingGeometry', 'inner_radius : Double, outer_radius : Double, theta_segments : Int'],
    ['IcosahedronGeometry', 'radius : Double, detail : Int'],
    ['CapsuleGeometry', 'radius : Double, height : Double, cap_segments : Int, radial_segments : Int'],
    ['EdgesGeometry', 'geometry : BufferGeometry, threshold_angle : Double'],
    ['WireframeGeometry', 'geometry : BufferGeometry'],
  ].map(([type, args]) => cls(type, args, geometry())),
  cls('Material', '', [
    p('user_data', 'UserData', 'userData'),
    p('id', 'Int'), p('kind', 'String', 'type'), ...rw('name', 'String'), ...rw('opacity', 'Double'),
    ...['transparent', 'visible', 'depth_test', 'depth_write'].flatMap(n => rw(n, 'Bool', n.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))),
    ...rw('side', 'Side'), ...rw('alpha_test', 'Double', 'alphaTest'),
    m('clone', '', 'Material'), m('dispose'), identity('Material'),
    expr('mark_needs_update', '', 'Unit', '{ self.needsUpdate = true; }'),
    nullable('as_standard_material', '', 'MeshStandardMaterial', 'self.isMeshStandardMaterial ? self : null'),
    nullable('as_physical_material', '', 'MeshPhysicalMaterial', 'self.isMeshPhysicalMaterial ? self : null'),
    nullable('as_basic_material', '', 'MeshBasicMaterial', 'self.isMeshBasicMaterial ? self : null'),
  ], { factory: null }),
  cls('MeshBasicMaterial', 'color : Int', [...colorMaterial(), ...rw('wireframe', 'Bool')]),
  cls('MeshStandardMaterial', 'color : Int, roughness : Double, metalness : Double', [
    ...colorMaterial(), ...rw('roughness', 'Double'), ...rw('metalness', 'Double'), ...rw('wireframe', 'Bool'),
    p('emissive', 'Color'), ...rw('emissive_intensity', 'Double', 'emissiveIntensity'),
    ...map('normal_map', 'normalMap'), ...map('roughness_map', 'roughnessMap'), ...map('metalness_map', 'metalnessMap'),
    ...map('emissive_map', 'emissiveMap'), ...map('ao_map', 'aoMap'), ...map('env_map', 'envMap'),
    p('normal_scale', 'Vector2', 'normalScale'), ...rw('normal_map_type', 'NormalMapType', 'normalMapType'),
    p('env_map_rotation', 'Euler', 'envMapRotation'), ...rw('flat_shading', 'Bool', 'flatShading'),
    ...['env_map_intensity', 'ao_map_intensity', 'bump_scale', 'displacement_scale', 'displacement_bias', 'light_map_intensity'].flatMap(n => rw(n, 'Double', n.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))),
    ...['bump_map', 'displacement_map', 'alpha_map', 'light_map'].flatMap(n => map(n, n.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))),
  ]),
  cls('MeshPhysicalMaterial', 'color : Int, roughness : Double, metalness : Double', [
    ...material(), upcast('standard_material', 'MeshStandardMaterial'),
    ...['clearcoat', 'transmission', 'thickness', 'ior', 'reflectivity', 'iridescence', 'sheen', 'anisotropy', 'dispersion'].flatMap(n => rw(n, 'Double')),
    ...['clearcoat_roughness', 'attenuation_distance', 'sheen_roughness', 'specular_intensity', 'anisotropy_rotation'].flatMap(n => rw(n, 'Double', n.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))),
    ...rw('iridescence_ior', 'Double', 'iridescenceIOR'),
    ...['attenuation_color', 'sheen_color', 'specular_color'].map(n => p(n, 'Color', n.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))),
    p('clearcoat_normal_scale', 'Vector2', 'clearcoatNormalScale'),
    expr('iridescence_thickness_range', '', 'FixedArray[Double]', 'self.iridescenceThicknessRange.slice()'),
    expr('set_iridescence_thickness_range', 'minimum : Double, maximum : Double', 'Unit', '{ self.iridescenceThicknessRange = [minimum, maximum]; }'),
    ...['clearcoat_map', 'clearcoat_roughness_map', 'clearcoat_normal_map', 'transmission_map', 'thickness_map', 'iridescence_map', 'iridescence_thickness_map', 'sheen_color_map', 'sheen_roughness_map', 'specular_color_map', 'specular_intensity_map', 'anisotropy_map'].flatMap(n => map(n, n.replace(/_([a-z])/g, (_, c) => c.toUpperCase()))),
  ]),
  cls('MeshPhongMaterial', 'color : Int, shininess : Double', [...colorMaterial(), ...rw('shininess', 'Double'), p('specular', 'Color'), p('emissive', 'Color')]),
  cls('MeshLambertMaterial', 'color : Int', [...colorMaterial(), p('emissive', 'Color')]),
  cls('MeshNormalMaterial', '', [...material(), ...rw('wireframe', 'Bool')]),
  cls('LineBasicMaterial', 'color : Int', [...colorMaterial(), ...rw('linewidth', 'Double')]),
  cls('PointsMaterial', 'color : Int, size : Double', [...colorMaterial(), ...rw('size', 'Double'), ...rw('size_attenuation', 'Bool', 'sizeAttenuation')]),
  cls('SpriteMaterial', 'color : Int', [...colorMaterial(), ...rw('rotation', 'Double')]),
  cls('Mesh', 'geometry : BufferGeometry, material : Material', [
    m('update_morph_targets', '', 'Unit', 'updateMorphTargets'),
    m('get_vertex_position', 'index : Int, target : Vector3', 'Vector3', 'getVertexPosition'),
    expr('morph_target_names', '', 'FixedArray[String]', 'Object.keys(self.morphTargetDictionary ?? {})'),
    expr('morph_target_influences', '', 'FixedArray[Double]', 'self.morphTargetInfluences?.slice() ?? []'),
    nullable('morph_target_index', 'name : String', 'Int', 'self.morphTargetDictionary && Object.hasOwn(self.morphTargetDictionary, name) ? self.morphTargetDictionary[name] : null'),
    nullable('morph_influence', 'index : Int', 'Double', 'index >= 0 && index < (self.morphTargetInfluences?.length ?? 0) ? self.morphTargetInfluences[index] : null'),
    expr('set_morph_influence', 'index : Int, weight : Double', 'Bool', '{ if (index < 0 || index >= (self.morphTargetInfluences?.length ?? 0)) return false; self.morphTargetInfluences[index] = weight; return true; }'),
    expr('set_morph_weight', 'name : String, weight : Double', 'Bool', '{ const dict = self.morphTargetDictionary; if (!dict || !Object.hasOwn(dict, name)) return false; const index = dict[name]; if (index < 0 || index >= (self.morphTargetInfluences?.length ?? 0)) return false; self.morphTargetInfluences[index] = weight; return true; }'),
    ...node(), p('geometry', 'BufferGeometry'), s('geometry', 'BufferGeometry'), s('material', 'Material'),
    expr('materials', '', 'FixedArray[Material]', 'Array.isArray(self.material) ? self.material.slice() : [self.material]'),
    expr('set_materials', 'materials : FixedArray[Material]', 'Unit', '{ self.material = materials.slice(); }'),
  ]),
  cls('SkinnedMesh', 'geometry : BufferGeometry, material : Material', [
    ...node(), upcast('mesh', 'Mesh'), nullable('skeleton', '', 'Skeleton', 'self.skeleton'),
    m('bind', 'skeleton : Skeleton, bind_matrix : Matrix4'), m('pose'), m('normalize_skin_weights', '', 'Unit', 'normalizeSkinWeights'),
  ]),
  cls('Bone', '', node()),
  cls('Skeleton', 'bones : FixedArray[Bone]', [
    expr('bones', '', 'FixedArray[Bone]', 'self.bones.slice()'), m('pose'), m('update'), m('dispose'),
    nullable('get_bone_by_name', 'name : String', 'Bone', 'self.getBoneByName(name)'),
  ]),
  cls('InstancedMesh', 'geometry : BufferGeometry, material : Material, count : Int', [
    ...node(), upcast('mesh', 'Mesh'), ...rw('count', 'Int'),
    m('set_matrix_at', 'index : Int, matrix : Matrix4', 'Unit', 'setMatrixAt'),
    m('get_matrix_at', 'index : Int, target : Matrix4', 'Unit', 'getMatrixAt'),
    m('set_color_at', 'index : Int, color : Color', 'Unit', 'setColorAt'),
    expr('mark_needs_update', '', 'Unit', '{ self.instanceMatrix.needsUpdate = true; if (self.instanceColor) self.instanceColor.needsUpdate = true; }'),
    m('compute_bounding_box', '', 'Unit', 'computeBoundingBox'), m('compute_bounding_sphere', '', 'Unit', 'computeBoundingSphere'), m('dispose'),
  ]),
  ...['Line', 'LineSegments', 'Points'].map(type => cls(type, 'geometry : BufferGeometry, material : Material', node())),
  cls('Sprite', 'material : SpriteMaterial', [...node(), p('center', 'Vector2')]),
  cls('Light', '', [...node(), p('color', 'Color'), ...rw('intensity', 'Double')], { factory: null }),
  cls('LightShadow', '', [p('map_size', 'Vector2', 'mapSize'), p('camera', 'Camera'), ...rw('bias', 'Double'), ...rw('normal_bias', 'Double', 'normalBias'), ...rw('radius', 'Double'), m('dispose')], { factory: null }),
  cls('AmbientLight', 'color : Int, intensity : Double', light()),
  cls('DirectionalLight', 'color : Int, intensity : Double', [...light(), p('target', 'Object3D'), p('shadow', 'LightShadow')]),
  cls('PointLight', 'color : Int, intensity : Double, distance : Double, decay : Double', [...light(), ...rw('distance', 'Double'), ...rw('decay', 'Double'), p('shadow', 'LightShadow')]),
  cls('SpotLight', 'color : Int, intensity : Double, distance : Double, angle : Double, penumbra : Double, decay : Double', [...light(), ...['distance', 'angle', 'penumbra', 'decay'].flatMap(n => rw(n, 'Double')), p('target', 'Object3D'), p('shadow', 'LightShadow')]),
  cls('HemisphereLight', 'sky_color : Int, ground_color : Int, intensity : Double', [...light(), p('ground_color', 'Color', 'groundColor')]),
  cls('Fog', 'color : Int, near : Double, far : Double', [p('color', 'Color'), ...rw('near', 'Double'), ...rw('far', 'Double')]),
  cls('FogExp2', 'color : Int, density : Double', [p('color', 'Color'), ...rw('density', 'Double')]),
  cls('Texture', '', [
    p('user_data', 'UserData', 'userData'),
    ...rw('mapping', 'TextureMapping'),
    identity('Texture'), m('clone', '', 'Texture'), ...rw('name', 'String'), p('offset', 'Vector2'), p('repeat', 'Vector2'), p('center', 'Vector2'),
    ...rw('rotation', 'Double'), ...rw('flip_y', 'Bool', 'flipY'), ...rw('anisotropy', 'Int'),
    ...rw('wrap_s', 'Wrapping', 'wrapS'), ...rw('wrap_t', 'Wrapping', 'wrapT'),
    ...rw('mag_filter', 'MagnificationFilter', 'magFilter'), ...rw('min_filter', 'MinificationFilter', 'minFilter'),
    expr('mark_needs_update', '', 'Unit', '{ self.needsUpdate = true; }'), m('update_matrix', '', 'Unit', 'updateMatrix'), m('dispose'),
  ]),
  cls('DataTexture', '', [upcast('texture', 'Texture'),
    expr('width', '', 'Int', 'self.image.width'), expr('height', '', 'Int', 'self.image.height'),
  ], { factory: { name: 'from_rgba', args: 'data : Bytes, width : Int, height : Int', js: 'dataTextureRGBA' } }),
  cls('PMREMGenerator', 'renderer : WebGLRenderer', [
    m('from_equirectangular', 'texture : Texture', 'WebGLRenderTarget', 'fromEquirectangular'),
    m('from_cubemap', 'texture : Texture', 'WebGLRenderTarget', 'fromCubemap'),
    m('compile_equirectangular_shader', '', 'Unit', 'compileEquirectangularShader'),
    m('compile_cubemap_shader', '', 'Unit', 'compileCubemapShader'), m('dispose'),
  ]),
  cls('CanvasTexture', 'canvas : Canvas', [upcast('texture', 'Texture')]),
  cls('WebGLRenderTarget', 'width : Int, height : Int', [p('texture', 'Texture'), p('width', 'Int'), p('height', 'Int'), m('set_size', 'width : Int, height : Int', 'Unit', 'setSize'), m('dispose')]),
  cls('WebGLRenderer', '', [
    p('dom_element', 'Canvas', 'domElement'),
    m('render', 'scene : Scene, camera : Camera'), m('set_pixel_ratio', 'ratio : Double', 'Unit', 'setPixelRatio'),
    m('get_pixel_ratio', '', 'Double', 'getPixelRatio'), m('get_size', 'target : Vector2', 'Vector2', 'getSize'),
    m('set_clear_color', 'color : Color, alpha : Double', 'Unit', 'setClearColor'),
    m('clear', 'color : Bool, depth : Bool, stencil : Bool'), ...rw('auto_clear', 'Bool', 'autoClear'),
    { ...optional('render_target', 'WebGLRenderTarget'), expression: '{ self.setRenderTarget(value); }' },
    m('read_render_target_pixels', 'target : WebGLRenderTarget, x : Int, y : Int, width : Int, height : Int, buffer : Bytes', 'Unit', 'readRenderTargetPixels'),
    m('set_animation_loop', 'callback : (Double) -> Unit', 'Unit', 'setAnimationLoop'),
    expr('stop_animation_loop', '', 'Unit', '{ self.setAnimationLoop(null); }'),
    expr('set_shadows_enabled', 'enabled : Bool', 'Unit', '{ self.shadowMap.enabled = enabled; }'),
    ...rw('tone_mapping', 'ToneMapping', 'toneMapping'), ...rw('tone_mapping_exposure', 'Double', 'toneMappingExposure'),
    m('dispose'), m('force_context_loss', '', 'Unit', 'forceContextLoss'),
  ], { factory: null }),
  cls('Canvas', '', [p('width', 'Int'), p('height', 'Int'), expr('append_to_body', '', 'Unit', '{ document.body.appendChild(self); }'), m('remove')], { factory: null }),
  ...[
    ['AxesHelper', 'size : Double'], ['GridHelper', 'size : Double, divisions : Int'],
    ['BoxHelper', 'object : Object3D, color : Int'], ['CameraHelper', 'camera : Camera'],
  ].map(([type, args]) => cls(type, args, [...node(), m('dispose')])),
  cls('Box3', '', [
    p('min', 'Vector3'), p('max', 'Vector3'), m('set', 'min : Vector3, max : Vector3', 'Box3'), m('set_from_object', 'object : Object3D', 'Box3', 'setFromObject'),
    m('get_center', 'target : Vector3', 'Vector3', 'getCenter'), m('get_size', 'target : Vector3', 'Vector3', 'getSize'),
    m('contains_point', 'point : Vector3', 'Bool', 'containsPoint'), m('intersects_box', 'box : Box3', 'Bool', 'intersectsBox'),
    m('expand_by_point', 'point : Vector3', 'Box3', 'expandByPoint'), m('union', 'box : Box3', 'Box3'), m('is_empty', '', 'Bool', 'isEmpty'), m('clone', '', 'Box3'),
  ]),
  cls('Sphere', 'center : Vector3, radius : Double', [p('center', 'Vector3'), ...rw('radius', 'Double'), m('contains_point', 'point : Vector3', 'Bool', 'containsPoint'), m('intersects_sphere', 'sphere : Sphere', 'Bool', 'intersectsSphere')]),
  cls('Raycaster', 'origin : Vector3, direction : Vector3', [
    p('layers', 'Layers'),
    ...rw('near', 'Double'), ...rw('far', 'Double'), m('set', 'origin : Vector3, direction : Vector3'),
    m('set_from_camera', 'coords : Vector2, camera : Camera', 'Unit', 'setFromCamera'),
    m('intersect_object', 'object : Object3D, recursive : Bool', 'FixedArray[Intersection]', 'intersectObject'),
    m('intersect_objects', 'objects : FixedArray[Object3D], recursive : Bool', 'FixedArray[Intersection]', 'intersectObjects'),
  ]),
  cls('Intersection', '', [p('distance', 'Double'), p('point', 'Vector3'), p('object', 'Object3D'), nullable('uv', '', 'Vector2', 'self.uv'), nullable('face_index', '', 'Int', 'self.faceIndex'), nullable('instance_id', '', 'Int', 'self.instanceId')], { factory: null }),
];

export const objectMethods = [
  p('user_data', 'UserData', 'userData'), p('layers', 'Layers'),
  ...rw('cast_shadow', 'Bool', 'castShadow'), ...rw('receive_shadow', 'Bool', 'receiveShadow'),
  ...rw('frustum_culled', 'Bool', 'frustumCulled'), ...rw('render_order', 'Int', 'renderOrder'),
  nullable('as_mesh', '', 'Mesh', 'self.isMesh ? self : null'),
  nullable('as_skinned_mesh', '', 'SkinnedMesh', 'self.isSkinnedMesh ? self : null'),
  nullable('as_camera', '', 'Camera', 'self.isCamera ? self : null'),
  nullable('as_light', '', 'Light', 'self.isLight ? self : null'),
];
export const sceneMethods = [
  nullable('background_texture', '', 'Texture', 'self.background?.isTexture ? self.background : null'), optional('background_texture', 'Texture', 'background'),
  nullable('environment', '', 'Texture', 'self.environment'), optional('environment', 'Texture'),
  nullable('fog', '', 'Fog', 'self.fog?.isFog ? self.fog : null'), optional('fog', 'Fog'),
  nullable('fog_exp2', '', 'FogExp2', 'self.fog?.isFogExp2 ? self.fog : null'), optional('fog_exp2', 'FogExp2', 'fog'),
];
